{% set name = "Flask-AppBuilder" %}
{% set version = "5.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/f/flask-appbuilder/flask_appbuilder-5.0.2.tar.gz
  sha256: f577b982a1ae40bc213238cedb93c39c67cf2199aa1e006e087ea1b3507d5450

build:
  entry_points:
    - fab = flask_appbuilder.cli:fab
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  # flask-limiter not built for versions <py310
  # https://github.com/alisaifee/flask-limiter/blob/8b111eb5f0298e5b095272027bf3194d2c999aa8/setup.py#L44
  skip: true  # [py<37]

requirements:
  host:
    - python
    - pip
    - setuptools
  run:
    - python
    - apispec >=6.0.0,<7
    # pyyaml is for apispec[yaml]
    - pyyaml >=3.10
    - colorama >=0.3.9,<1
    - click >=8,<9
    - email-validator >=1.0.5
    - flask >=2,<4
    - flask-babel >=3,<5
    - flask-limiter >3,<4
    - flask-login >=0.3,<0.7
    - flask-sqlalchemy >=2.4.0,<4
    - flask-wtf >=0.14.2,<2
    - flask-jwt-extended >=4.0.0,<5.0.0
    - jsonschema >=3,<5
    - marshmallow >=3.18.0,<5
    - marshmallow-sqlalchemy >=0.22.0,<3.0.0
    - python-dateutil >=2.3,<3
    - prison >=0.2.1,<1.0.0
    - pyjwt >=2.0.0,<3.0.0
    - sqlalchemy >=1.4.0,<3
    - sqlalchemy-utils >=0.32.21,<1
    - wtforms <4
    - werkzeug <4
  run_constrained:
    # jmespath
    - jmespath >=0.9.5
    # oauth
    - Authlib >=0.14,<2.0.0
    # talisman
    - flask-talisman >=1.0.0,<2.0

# E   ModuleNotFoundError: No module named 'ldap'
{% set ignore_tests = " --ignore=tests/security/test_auth_ldap.py" %}
# E   ModuleNotFoundError: No module named 'hiro'
{% set ignore_tests = ignore_tests + " --ignore=tests/security/test_mvc_security.py" %}
{% set ignore_tests = ignore_tests + " --ignore=tests/security/test_password_complexity.py" %}
{% set ignore_tests = ignore_tests + " --ignore=tests/security/test_rate_limiter.py" %}
{% set ignore_tests = ignore_tests + " --ignore=tests/test_addon.py" %}
{% set ignore_tests = ignore_tests + " --ignore=tests/test_api.py" %}
{% set ignore_tests = ignore_tests + " --ignore=tests/test_custom_indexview.py" %}
{% set ignore_tests = ignore_tests + " --ignore=tests/test_fab_cli.py" %}
{% set ignore_tests = ignore_tests + " --ignore=tests/test_menu.py" %}
{% set ignore_tests = ignore_tests + " --ignore=tests/test_mvc.py" %}
{% set ignore_tests = ignore_tests + " --ignore=tests/test_mvc_oauth.py" %}
{% set ignore_tests = ignore_tests + " --ignore=tests/test_security_api.py" %}
{% set ignore_tests = ignore_tests + " --ignore=tests/test_urltools.py" %}

test:
  source_files:
    - tests
  imports:
    - flask_appbuilder
    - flask_appbuilder._compat
    - flask_appbuilder.actions
    - flask_appbuilder.api
    - flask_appbuilder.babel
    - flask_appbuilder.basemanager
    - flask_appbuilder.baseviews
    - flask_appbuilder.charts.views
    - flask_appbuilder.cli
    - flask_appbuilder.const
    - flask_appbuilder.exceptions
    - flask_appbuilder.fields
    - flask_appbuilder.fieldwidgets
    - flask_appbuilder.filemanager
    - flask_appbuilder.filters
    - flask_appbuilder.forms
    - flask_appbuilder.hooks
    - flask_appbuilder.menu
    - flask_appbuilder.models
    - flask_appbuilder.security
    - flask_appbuilder.urltools
    - flask_appbuilder.utils
    - flask_appbuilder.validators
    - flask_appbuilder.views
    - flask_appbuilder.widgets
  requires:
    - pip
    - pytest
    - parameterized
    - authlib
    - jmespath
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    - pytest -v tests {{ ignore_tests }}
    - fab --help

about:
  home: https://github.com/dpgaspar/flask-appbuilder
  license_file: LICENSE
  license: BSD-3-Clause
  license_family: BSD
  summary: Simple and rapid application development framework, built on top of Flask.
  description: Simple and rapid application development framework, built on top of Flask, includes detailed security, auto CRUD generation for your models, google charts and much more.
  dev_url: https://github.com/dpgaspar/flask-appbuilder
  doc_url: https://flask-appbuilder.readthedocs.io

extra:
  recipe-maintainers:
    - halldc
    - xylar
