{% set name = "Flask-AppBuilder" %}
{% set version = "3.4.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a9fb668240bebd63a9e40376ad30f7d704065060bf231c61c78cd7196c396b27

build:
  noarch: python
  entry_points:
    - fabmanager = flask_appbuilder.console:cli
  number: 1
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools
    - wheel

  run:
    - python >=3.6
    - apispec[yaml] >=3.3,<4
    - colorama >=0.3.9,<1
    - click >=6.7,<9
    - email-validator >=1.0.5,<2
    - flask >=0.12,<2
    - flask-babel >=1
    - flask-login >=0.3,<0.5
    - flask-openid >=1.2.5,<2
    # From upstream: SQLAlchemy 1.4.0 breaks flask-sqlalchemy and sqlalchemy-utils
    - sqlalchemy <1.4.0
    - flask-sqlalchemy >=2.4,<3
    - flask-wtf >=0.14.2,<0.15.0
    - flask-jwt-extended >=3.18,<4
    - jsonschema >=3.0.1,<4
    - marshmallow >=3,<4
    - marshmallow-enum >=1.5.1,<2
    - marshmallow-sqlalchemy >=0.22.0,<0.24.0
    - prison >=0.1.3,<1.0.0
    - pyjwt >=1.7.1,<2.0.0
    - python-dateutil >=2.3,<3
    - sqlalchemy-utils >=0.32.21,<1
    - werkzeug
    # 5/12/2021: extras_require from upstream source
    - jmespath >=0.9.5
    # 5/12/2021: marshmallow-enum 1.5.1 requires enum34
    - enum34

test:
  imports:
    - flask_appbuilder
    - flask_appbuilder.babel
    - flask_appbuilder.charts
    - flask_appbuilder.models
    - flask_appbuilder.models.generic
    - flask_appbuilder.models.mongoengine
    - flask_appbuilder.models.sqla
    - flask_appbuilder.security
    - flask_appbuilder.security.mongoengine
    - flask_appbuilder.security.sqla
    - flask_appbuilder.tests
    - flask_appbuilder.translations
  requires:
    #- pip
  commands:
    # 2021/7/28: flask-appbuilder 3.3.2 has requirement Flask-Babel<2,>=1, but we have only flask-babel 2.0.0
    # and it works. The flask-appbuilder maintainers didn't update the version Flask-Babel in requirements two years, 
    # but the last release 2.0.0 was at Aug 27, 2020.
    #- pip check
    - fabmanager --help

about:
  home: http://flaskappbuilder.pythonanywhere.com/
  license_file: LICENSE
  license: BSD 3-Clause
  license_family: BSD
  summary: 'Simple and rapid application development framework, built on top of Flask. includes detailed security, auto CRUD generation for your models, google charts and much more.'
  dev_url: https://github.com/dpgaspar/flask-appbuilder/
  doc_url: https://github.com/dpgaspar/flask-appbuilder/

extra:
  recipe-maintainers:
    - pmlandwehr
    - halldc
    - xylar
