{% set name = "Flask-AppBuilder" %}
{% set version = "1.9.2" %}
{% set bundle = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash_val = "85fa363c5e5e6402f310c1bf00c8b6358d2089f8720897e6d8014a390686863e" %}
{% set build = 0 %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  {{ hash_type }}: {{ hash_val }}

build:
  skip: True  # [py36]
  entry_points:
    - fabmanager = flask_appbuilder.console:cli
  
  number: {{ build }}
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - colorama >=0.3
    - click >=3.0
    - flask >=0.10
    - flask-babel >=0.10.0
    - flask-login ==0.2.11
    - flask-openid >=1.1.0
    - flask-sqlalchemy >=2.0,<2.1.99
    - flask-wtf >=0.12

test:
  imports:
    - examples
    - flask_appbuilder
    - flask_appbuilder.babel
    - flask_appbuilder.charts
    - flask_appbuilder.models
    - flask_appbuilder.models.generic
    - flask_appbuilder.models.mongoengine
    - flask_appbuilder.models.sqla
    - flask_appbuilder.security
    - flask_appbuilder.security.mongoengine
    - flask_appbuilder.security.sqla
    - flask_appbuilder.tests
    - flask_appbuilder.translations

  commands:
    - fabmanager --help

about:
  home: http://flaskappbuilder.pythonanywhere.com/
  license_file: LICENSE
  license: BSD 3-Clause
  license_family: BSD
  summary: 'Simple and rapid application development framework, built on top of Flask. includes detailed security, auto CRUD generation for your models, google charts and much more.'
  dev_url: https://github.com/dpgaspar/flask-appbuilder/
  doc_url: https://github.com/dpgaspar/flask-appbuilder/

extra:
  recipe-maintainers:
    - pmlandwehr
