travis:
  secure:
    BINSTAR_TOKEN: izqM/g0TQoc8gkLQPmXQ9+kQgAH8NPiRw13gRpPh9ZcWkB195HTgNvzszg2PQm2BlwwdVfOYsakATyazMr7FJ6MZynoWDYypfJsKZrg8rdW16ON/OsMp6pPnHYi2s4rm1MReVJhnL/9bZZKg/JLysfaCmFgO4epZ3B4LZhCbUdA9Js0KXVrRPwKGDUK2BEMp5AnLNnOZcY4WQKbgBY5YWtOrtGaCAh1PFe2LhghQo759JynXkmJWrCFGzIwQLJBXRbh+YWDrWPlNjYN2avnqVY7oJWGaR2svVVSKcTUsh/RLfKnnmxOuscvwGeTEbt0sfwHZ0JOj8e5xWC6Ekgesb++tbBYuBLz/FImduTWY1onNhDsEuW4075wnx48Do1CI31wiEWMim0IYM+ZKmPfD9lzMl/MJxmjQGBiBGqpg1hFkmi28FvTE+3XDBeHxFrFj68az9d3kB/UOUbUvG2+7K8ExyhJpnNUs6u8EIxg3M6wTpusxsdaii2Yym8ebXfveB6e3lcftlFijNUp5VsQpjkhprA+1g7ZWD3UWCuqFs/h5uGYQxICNe6VsUzm6rnYbLLklhVdRmjohaGL500vctC4hfEjXNM5xsJsVoOpqZERgZ7I9gNArneErcErPjJj3wkbXxp/XqR7dhJTSyc8kVkzU1bpaF0+G7MMCZcB9T3c=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
