travis:
  secure:
    BINSTAR_TOKEN: UAWrhq8QsCixVzqc3YeTaARSVEPRrbb/9pB0niu6gck/GkXaJA9TgVv8JGTwBbigv6lwbssAH0nY4BSyOO+5ltJ+gNWU/OXy/OyJvEUbzcNnLF08U6vHfOzlhgz6u9gR3/g7TH7ihl80KTIZYDQILThzUBmRg2sc3GAEdcglA5EMWRC+a2xrb+kc97svF1kgWNPzN3eLlrOlAS4Rdvhzw3yTgf7u4Xr/aKm45Jl0FL6db85MoQfzrg97EnREAu0lqd4nGc88YNGgIBdYOc5Ept5ub4GvVvDjji/bGLSl2ngMpl7bQIQYDlTOmMkIpBazUA1xImxy3w70eIf3wvLJBuFlVt98kz/vy7ylq8nC9VwXk+HeaxDLEoe6HpE5uX8bVCF4efubeDb7QzNijoQow4zU4mejs+bHdqHGdhFO2/XHr74JAMIMVncNMtwI8rxniJv72OU20rSYgxl5M2qTYqa6+Mk44nK49Iigt0ROumlYjxErttkyaHXzW7jXJaCTGuBwam23FS/uZ5BTFA9LOVCX7GVlmjYrlOihEN1DmU3AAeJNa7bZDkpqZjHJ4IttOJzlo4cljOy2FalWOsuWHTYwSfbdZz1M9ELtzpklg2vADMGSZvafoA3Xix8k9xHRsDKt+gbJvwMICkKmv5zujPChQP0U3eEfFR7hS2EKUVg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
